version: 2

# Build PDF & ePub
formats:
  - epub
  - pdf
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
     # You can also specify other tool versions:
     # nodejs: "18"
     # rust: "1.64"

python:
   install:
   - method: pip
     path: .   
   
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true