version: 2

# Build PDF & ePub
formats:
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      path: another/package
  system_packages: true

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true